### ISSUE TITLE
parse_image

### ISSUE THREAD

**Issue by MayDGT** [MTammvee/openpilot-supercombo-model#1]
Hi, MTammvee!  I know the model input should be (1,12,128,256) but why we need the function: parse_image() ?
I would appreciate it if you could reply to me！

**Comment by MTammvee** [comment]
Hi Radas,

The phone that they are using is known information. From there I searched
for the camera model that specific phone model has. The camera output is
yuv_420. This raw_camera output is also mentioned in their openpilot code.

Model is trained on their own images, which are transformed specific to their used camera (described with intrinsic and extrinsic camera matrices). If You want to make the model more accurate, You need to get Your own camera matrices. The transformations are mentioned here: https://github.com/commaai/openpilot/tree/master/common/transformations.
